# from django.core.exceptions import ValidationError


class NotificationValidator:
    def __init__(self): ...

    def __call__(self):
        return True


class UsernotificationValidator:
    def __init__(self): ...

    def __call__(self):
        return True
